language: node_js

node_js:
  - stable

before_install:  sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
  - npm test

